### ISSUE TITLE
Add custom location

### ISSUE THREAD

**Issue by relsakata** [Pixeluted/KrampUI#10]
add custom location for injector
instead of AppData\Roaming\KrampUI
you can set it to something else

**Comment by Pixeluted** [comment]
Hi, we might consider placing all the folders and files, in the folder where KrampUI exe is located

**Comment by Pixeluted** [comment]
Placing all the folders and files, in the folder where KrampUI exe is located will be implemented in v2 release, thank for your suggestion.
