### ISSUE TITLE
KrampUI not opening when i open it

### ISSUE THREAD

**Issue by Aydenhelper** [Pixeluted/KrampUI#5]
When I try to open KrampUI, nothing happens, no application, it just runs in the background in task manager., my first time tying. I've tried some troubleshooting steps with krampus helpers but it just didnt work. idk why its doing this, its been like this every krampui update. Yes all my antivirus software is off.

**Comment by Pixeluted** [comment]
Is this issue present on the latest one? If yes, try to reinstall webview, if you arent on latest version then please update
